SPLIT_KEYBOARD = yes
DEFAULT_FOLDER = sofle/rev1
SWAP_HANDS_ENABLE = yes



EE_HANDS = yes
LOCKING_SUPPORT_ENABLE = yes
LOCKING_RESYNC_ENABLE = yes
SCROLL_LOCK_ENABLE = yes
CAPS_LOCK_ENABLE = yes
EXTRAKEY_ENABLE = yes

DYNAMIC_KEYMAP_LAYER_COUNT = yes

RGBLIGHT_SPLIT = yes

RGBLIGHT_LAYERS = yes
RGBLIGHT_LAYERS_OVERRIDE_RGB_OFF = yes

SPLIT_LAYER_STATE_ENABLE = yes
SPLIT_LED_STATE_ENABLE = yes
SPLIT_MODS_ENABLE = yes
SPLIT_OLED_ENABLE = yes

USER_LIGHT_UPDATE = yes

CONVERT_TO=elite_pi
BOOTLOADER = rp2040
